horeca_api_request_delivery:
    path: /api/delivery/request
    controller: Horeca\MiddlewareClientBundle\Controller\HorecaApiController::requestDelivery
    methods: [POST]

horeca_api_order_send:
    path: /api/order/send
    controller: Horeca\MiddlewareClientBundle\Controller\HorecaApiController::receiveOrder
    methods: [POST]

horeca_api_order_update:
    path: /api/order/update
    controller: Horeca\MiddlewareClientBundle\Controller\HorecaApiController::receiveOrderUpdate
    methods: [POST]

horeca_api_notification_view:
    path: /api/notification/view
    controller: Horeca\MiddlewareClientBundle\Controller\HorecaApiController::viewNotification
    methods: [GET]

horeca_api_shop_initialize:
    path: /api/shop/initialize
    controller: Horeca\MiddlewareClientBundle\Controller\HorecaApiController::initializeShop
    methods: [POST]

horeca_api_shop_availability:
    path: /api/tenant/shop/availability
    controller: Horeca\MiddlewareClientBundle\Controller\HorecaApiController::updateShopAvailability
    methods: [POST]

horeca_api_shop:
    path: /api/tenant/shop/update
    controller: Horeca\MiddlewareClientBundle\Controller\HorecaApiController::updateShop
    methods: [POST]
