parameters:
#    horeca.api_key: '%env(resolve:HORECA_API_KEY)%'
#    horeca.enable_request_exception_logging: '%env(resolve:HORECA_ENABLE_REQUEST_EXCEPTION_LOGGING)%'
#    horeca.order_notification_messenger_transport: 'hmc_order_notification'

services:

    Horeca\MiddlewareCommonLib\Service\HorecaApiInterface:
        class: Horeca\MiddlewareCommonLib\Service\HorecaApiService
        arguments:
            - '@jms_serializer'
        calls:
            - [ setBaseUrl, [ '%env(resolve:HORECA_BASE_URL)%' ] ]
            - [ setApiKey, [ '%env(resolve:HORECA_API_KEY)%' ] ]
            - [ setMiddlewareClientId, [ '%env(resolve:HORECA_MIDDLEWARE_CLIENT_ID)%' ] ]

    Horeca\MiddlewareClientBundle\Service\RequestService:
        arguments:
            - '@logger'
            - '@doctrine.orm.entity_manager'

    Horeca\MiddlewareClientBundle\EventListener\RequestListener:
        arguments:
            - '@logger'
            - '@Horeca\MiddlewareClientBundle\Service\RequestService'
            - '%horeca.enable_request_exception_logging%'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    Horeca\MiddlewareClientBundle\MessageHandler\OrderNotificationMessageHandler:
        arguments:
            $transport: '%horeca.order_notification_messenger_transport%'
        calls:
            - [ setLogger,[ '@logger' ] ]
            - [ setSerializer,[ '@jms_serializer' ] ]
            - [ setProviderApi,[ '@Horeca\MiddlewareClientBundle\Service\ProviderApiInterface' ] ]
            - [ setHorecaApiService,[ '@Horeca\MiddlewareCommonLib\Service\HorecaApiInterface' ] ]
            - [ setEntityManager,[ '@doctrine.orm.entity_manager' ] ]
        tags:
            - { name: messenger.message_handler }
