parameters:
    horeca.base_url: '%env(resolve:HORECA_BASE_URL)%'
    horeca.api_key: '%env(resolve:HORECA_API_KEY)%'
    horeca.shared_key: '%env(resolve:HORECA_SHARED_KEY)%'
    horeca.middleware_client_id: '%env(resolve:HORECA_MIDDLEWARE_CLIENT_ID)%'
    horeca.enable_request_exception_logging: '%env(resolve:HORECA_ENABLE_REQUEST_EXCEPTION_LOGGING)%'

services:

    Horeca\MiddlewareCommonLib\Service\HorecaApiInterface:
        class: Horeca\MiddlewareCommonLib\Service\HorecaApiService
        arguments:
            - '@jms_serializer'
        calls:
            - [ setBaseUrl, [ '%horeca.base_url%' ] ]
            - [ setApiKey, [ '%horeca.api_key%' ] ]
            - [ setMiddlewareClientId, [ '%horeca.middleware_client_id%' ] ]

    Horeca\MiddlewareClientBundle\EventListener\RequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
        calls:
            - [ enableRequestExceptionLogging, [ '%horeca.enable_request_exception_logging%' ] ]
