parameters:
    horeca.enable_request_exception_logging: '%env(default:false:HORECA_ENABLE_REQUEST_EXCEPTION_LOGGING)%'

services:

    Horeca\MiddlewareClientBundle\Controller\HorecaApiController:
        calls:
            - [ setLogger,[ '@logger' ] ]
            - [ setSerializer,[ '@jms_serializer' ] ]
            - [ setMessageBus,[ '@messenger.bus.default' ] ]
            - [ setEntityManager,[ '@doctrine.orm.entity_manager' ] ]
        public: true

    Horeca\MiddlewareClientBundle\MessageHandler\OrderNotificationMessageHandler:
        arguments:
            $transport: '%horeca.order_notification_messenger_transport%'
        calls:
            - [ setLogger,[ '@logger' ] ]
            - [ setSerializer,[ '@jms_serializer' ] ]
            - [ setProviderApi,[ '@Horeca\MiddlewareClientBundle\Service\ProviderApiInterface' ] ]
            - [ setEntityManager,[ '@doctrine.orm.entity_manager' ] ]
            - [ setProtocolActionsService,[ '@Horeca\MiddlewareClientBundle\Service\ProtocolActionsService' ] ]
        tags:
            - { name: messenger.message_handler }

    Horeca\MiddlewareClientBundle\Command\InitBundleCommand:
        arguments:
            $container: '@service_container'
        tags:
            - { name: console.command }

    Horeca\MiddlewareClientBundle\Command\CreateUserCommand:
        calls:
            - [ setUserPasswordHasherInterface,[ '@security.user_password_hasher' ] ]
            - [ setEntityManager,[ '@doctrine.orm.entity_manager' ] ]
        tags:
            - { name: console.command }
